import { Asset } from "@/types";

const {
    valquiria,
    melanie,
    walter,
    dario,
    malagy,
    edicelio,
    fenilde,
}: Record<string, Asset> = {
    valquiria: {
        id: "valquiria",
        name: "Valquiria Pondja",
        url: "/images/team/valquiria-288*288.png",
        alt: "Valquiria Pondja",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 288,
            height: 288,
        },
    },
    melanie: {
        id: "melanie",
        name: "Melanie Nhanzilo",
        url: "/images/team/melanie-288*288.png",
        alt: "Melanie",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 288,
            height: 288,
        },
    },
    walter: {
        id: "walter",
        name: "Walter Cumbucane",
        url: "/images/team/walter-288*288.png",
        alt: "Walter",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 288,
            height: 288,
        },
    },
    dario: {
        id: "dario",
        name: "Dario Pacule",
        url: "/images/team/dario-288*288.png",
        alt: "Dario",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 288,
            height: 288,
        },
    },
    malagy: {
        id: "malagy",
        name: "Malagy Cassimo",
        url: "/images/team/malagy-288*288.png",
        alt: "Malagy",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 288,
            height: 288,
        },
    },
    edicelio: {
        id: "edicelio",
        name: "Edicelio Savanguane",
        url: "/images/team/edicelio-288*288.png",
        alt: "Edicelio",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 288,
            height: 288,
        },
    },
    fenilde: {
        id: "fenilde",
        name: "Fenilde",
        url: "/images/team/fenilde-288*288.png",
        alt: "Fenilde",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 288,
            height: 288,
        },
    },
};

const { mozdevz }: Record<string, Asset> = {
    mozdevz: {
        id: "mozdevz",
        name: "MozDevz",
        url: "/images/brand/mozdevz-300*43.svg",
        alt: "MozDevz - A maior comunidade de desenvolvedores de Moçambique",
        mimeType: "image/svg+xml",
        type: "image",
        metadata: {
            width: 300,
            height: 43,
        },
    },
};

const {
    oxfam,
    vodacom,
    espaco,
    world_bank,
    kabum,
    ministerio,
    agencia_nacional,
    reino,
    ciuem,
    cowl,
    standard_bank,
    psi,
}: Record<string, Asset> = {
    oxfam: {
        id: "oxfam",
        name: "Oxfam",
        url: "/images/partners/oxfam-100*100.png",
        alt: "Oxfam - A maior organização de desenvolvimento de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 100,
            height: 100,
        },
    },
    vodacom: {
        id: "vodacom",
        name: "Vodacom",
        url: "/images/partners/vodacom-100*100.png",
        alt: "Vodacom - A maior operadora de telecomunicações de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 100,
            height: 100,
        },
    },
    espaco: {
        id: "espaco",
        name: "Espaço",
        url: "/images/partners/espaco-de-inovacao-120*68.png",
        alt: "Espaço - A maior empresa de tecnologia de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 120,
            height: 68,
        },
    },
    world_bank: {
        id: "world_bank",
        name: "The World Bank",
        url: "/images/partners/the-world-bank-120*90.png",
        alt: "The World Bank - A maior instituição financeira internacional",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 120,
            height: 90,
        },
    },
    kabum: {
        id: "kabum",
        name: "Kabum",
        url: "/images/partners/kabum-120*24.png",
        alt: "Kabum - A maior empresa de tecnologia de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 120,
            height: 24,
        },
    },
    ministerio: {
        id: "ministerio",
        name: "Ministério da Ciência, Tecnologia e Ensino Superior",
        url: "/images/partners/ministerio-120*150.png",
        alt: "Ministério da Ciência, Tecnologia e Ensino Superior - A maior instituição governamental de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 120,
            height: 150,
        },
    },
    agencia_nacional: {
        id: "agencia_nacional",
        name: "Agência Nacional de Desenvolvimento Geo-Espacial",
        url: "/images/partners/agencia-nacional-100*123.png",
        alt: "Agência Nacional de Desenvolvimento Geo-Espacial - A maior instituição governamental de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 100,
            height: 123,
        },
    },
    reino: {
        id: "reino",
        name: "Reino dos Paises Baixos",
        url: "/images/partners/reino-120*44.png",
        alt: "Reino dos Paises Baixos - A maior instituição governamental de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 120,
            height: 44,
        },
    },
    ciuem: {
        id: "ciuem",
        name: "Centro de Informação e Utilização da Energia",
        url: "/images/partners/ciuem-100*100.png",
        alt: "Centro de Informação e Utilização da Energia - A maior instituição governamental de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 100,
            height: 100,
        },
    },
    cowl: {
        id: "cowl",
        name: "Centro de Operações de Logística e Transporte",
        url: "/images/partners/cowl-100*100.png",
        alt: "Centro de Operações de Logística e Transporte - A maior instituição governamental de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 100,
            height: 100,
        },
    },
    standard_bank: {
        id: "standard_bank",
        name: "Standard Bank",
        url: "/images/partners/standard-bank-100*105.png",
        alt: "Standard Bank - A maior instituição governamental de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 100,
            height: 105,
        },
    },
    psi: {
        id: "psi",
        name: "Programa de Sustentabilidade e Inovação",
        url: "/images/partners/psi-100*100.png",
        alt: "Programa de Sustentabilidade e Inovação - A maior instituição governamental de Moçambique",
        mimeType: "image/png",
        type: "image",
        metadata: {
            width: 100,
            height: 100,
        },
    },
};

export {
    mozdevz,
    valquiria,
    walter,
    melanie,
    dario,
    malagy,
    edicelio,
    fenilde,
    oxfam,
    vodacom,
    espaco,
    world_bank,
    kabum,
    ministerio,
    agencia_nacional,
    reino,
    ciuem,
    cowl,
    standard_bank,
    psi,
};
